
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/01_unzip_data.ipynb

from zipfile import ZipFile
from pathlib import Path

PATH_RAW_DATA = Path('../data/raw/')
PATH_INTERIM_DATA = Path('../data/interim/')
PATH_TRANSCRIPT_ZIP = PATH_RAW_DATA / 'Transcripts.zip'

def unzip_transcripts(file:Path=PATH_TRANSCRIPT_ZIP):
    with ZipFile(str(file), 'r') as zf:
        zf.extractall(str(PATH_INTERIM_DATA))